app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/demodb
    username: postgres
    password:
    pool-size: 30

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      url: jdbc:postgresql://localhost:5432/demodb
      username: postgres
      password:
      driver-class-name: org.postgresql.Driver
